/*
 * Audio Normalizer - translations for the settings page.
 *
 * English is the source language and it is also what configPage.html carries literally, so the
 * page stays readable if this file ever fails to load. Ukrainian overrides it at runtime.
 *
 * Adding a language: copy the "en" block, translate the values, keep the keys, and add the
 * matching <option> to the language select in configPage.html. Nothing else needs touching.
 *
 * {name} placeholders are substituted by t() in configPage.js and must survive translation.
 */
(function () {
    'use strict';

    window.AudioNormalizerStrings = {

        en: {
            'lbl.language': 'Page language',

            'intro': 'Builds an <strong>additional</strong> audio track next to a film: louder dialogue, '
                + 'quieter explosions. The original file is not modified - the player simply gains one '
                + 'more audio option, and you can switch between them freely.',

            'diag.title': 'System status',
            'diag.checking': 'Checking…',
            'diag.unknownPath': 'unknown',
            'diag.missingFilters': 'Missing filters: {list}',
            'diag.allFiltersPresent': 'Every required filter is present.',
            'diag.candidates': 'Media items eligible for processing: {n}',
            'diag.failed': 'Could not read the status.',

            'sec.thresholds': 'Loudness thresholds',
            'lbl.targetLufs': 'Target loudness (LUFS)',
            'desc.targetLufs': 'The average level of the finished track. −16 suits watching at home, '
                + '−23 is the broadcast standard (quieter).',
            'lbl.maxPeak': 'Maximum peak (dBTP) - the ceiling',
            'desc.maxPeak': 'Nothing rises above this. −1.5 is safe on any device.',
            'lbl.targetLra': 'Allowed quiet-to-loud range (LU)',
            'desc.targetLra': 'How much dynamics to keep. An action film usually has 20-25 LU. '
                + '9 is comfortable at night, 14 still feels cinematic.',
            'lbl.skipBelow': 'Skip if the range is below (LU)',
            'desc.skipBelow': 'Even audio gains nothing from a second track - only disk space.',

            'sec.processing': 'Processing',
            'lbl.engine': 'Engine',
            'desc.engine': 'A plain compressor only removes the loud parts, it never makes dialogue '
                + 'more audible. dynaudnorm lifts the quiet passages, which is what actually solves this.',
            'opt.engine.Dynaudnorm': 'dynaudnorm - lifts the quiet, holds back the loud (recommended)',
            'opt.engine.SpeechNorm': 'speechnorm - speech oriented',
            'opt.engine.Compressor': 'Compressor - the gentlest, keeps the most dynamics',
            'opt.engine.LoudnessOnly': 'Level the loudness only, leave the dynamics alone',
            'chk.autoStrength': 'Pick the strength automatically for each film',
            'lbl.strength': 'Strength, 0-100',

            'sec.channels': 'Channels',
            'lbl.downmix': 'Channel layout',
            'desc.downmix': 'A plain 5.1 to stereo downmix makes dialogue <em>quieter</em>: on the test '
                + 'material −37.5 LUFS turned into −44.8. The dialogue matrix is not a luxury.',
            'opt.downmix.DialogueStereo': 'Dialogue-forward stereo (recommended)',
            'opt.downmix.PlainStereo': 'Plain stereo',
            'opt.downmix.KeepLayout': 'Keep the original layout (5.1/7.1)',
            'lbl.center': 'Centre channel (dialogue), dB',
            'lbl.surround': 'Surround channels, dB',
            'lbl.lfe': 'LFE subwoofer, dB',
            'desc.lfe': '−60 mutes LFE entirely. That is where most of the action-film boom lives.',

            'sec.trackFile': 'Track file',
            'lbl.codec': 'Codec',
            'opt.codec.Aac': 'AAC - plays everywhere including the browser (21 ms delay, compensated)',
            'opt.codec.Eac3': 'E-AC3 - exact length, great on TVs, browsers cannot decode it',
            'opt.codec.Ac3': 'AC3 - the same, friendlier to older receivers',
            'opt.codec.Flac': 'FLAC - lossless, zero delay, 3-5 times the file size',
            'opt.codec.Opus': 'Opus - the smallest, weaker support on older TVs',
            'lbl.container': 'Container',
            'opt.container.Mka': '.mka - keeps the language and the track title (recommended)',
            'opt.container.M4a': '.m4a - keeps the language, loses the title',
            'opt.container.Raw': 'Raw stream - no tags at all, only the file name',
            'lbl.bitrate': 'Bitrate, kbps',
            'lbl.prefix': 'Track title prefix',
            'desc.prefix': 'Placed in front of the name: <code>AN - Ukrainian 5.1</code>. That is how '
                + 'normalized tracks stand out in the player audio list.',
            'chk.appendSource': 'Append the source track name after the prefix',
            'lbl.fallbackTitle': 'Fallback title',
            'desc.fallbackTitle': 'Used when there is nothing to take from the source track. Avoid the '
                + 'words default, forced, foreign, cc, hi, sdh - Jellyfin reads them as flags, not as a name.',
            'chk.makeDefault': 'Make the normalized track the default one',
            'lbl.delay': 'Manual delay, ms',
            'desc.delay': 'Leave at 0. Only needed when a particular client ignores the codec delay and '
                + 'the sound visibly drifts from the picture.',

            'sec.background': 'Background work',
            'lbl.parallel': 'Parallel jobs',
            'chk.pause': 'Pause while somebody is watching',
            'chk.dryRun': 'Dry run: write nothing, only report what would be done',
            'chk.logCommands': 'Write the full ffmpeg command to the server log',
            'lbl.minFree': 'Keep free disk space, GB',
            'lbl.minDuration': 'Skip anything shorter than, min',
            'lbl.sourceSel': 'Which track to use as the source',
            'opt.src.MostChannels': 'The one with the most channels',
            'opt.src.DefaultTrack': 'The default one',
            'opt.src.PreferredLanguage': 'By preferred language',
            'lbl.langs': 'Preferred languages, comma separated',
            'btn.save': 'Save',
            'msg.saveFailed': 'Could not save the settings. Details are in the server log.',

            'sec.queue': 'Queue',
            'queue.line': 'Queued: {pending} · running: {running} · finished: {done} · failed: {failed}',
            'queue.pausedPlayback': ' · paused, playback in progress',
            'btn.analyzeAll': 'Measure the whole library',
            'btn.generateAll': 'Build tracks where needed',
            'btn.cancelQueue': 'Empty the queue',
            'msg.queuedAnalyze': 'Queued for measurement: {n}',
            'msg.queuedGenerate': 'Queued for building: {n}',
            'msg.dequeued': 'Removed from the queue: {n}',

            'sec.report': 'Media report',
            'chk.onlyProblems': 'Only those whose range exceeds the target',
            'desc.report': 'Click a <b>film name</b> to expand its audio tracks and tick the ones to '
                + 'normalize. Click a column heading to sort. "Quiet" and "Loud" are the bounds the '
                + 'loudness moves between; the "Range" between them is what hurts the ears.',
            'th.name': 'Name',
            'th.minutes': 'Min',
            'th.tracks': 'Trk',
            'th.tracks.tip': 'How many tracks are selected for normalizing',
            'th.source': 'Source',
            'th.lufs': 'LUFS',
            'th.lufs.tip': 'Average loudness of the original',
            'th.range': 'Range',
            'th.range.tip': 'Difference between quiet and loud in the original',
            'th.quiet': 'Quiet',
            'th.quiet.tip': 'Lower loudness bound: roughly the level of quiet dialogue',
            'th.loud': 'Loud',
            'th.loud.tip': 'Upper loudness bound: roughly the level of the loud scenes',
            'th.peak': 'Peak',
            'th.peak.tip': 'Peak level of the original',
            'th.after': 'After',
            'th.after.tip': 'The range once processed',
            'th.state': 'State',
            'th.mb': 'MB',

            'report.empty': 'Nothing here yet. Run "Measure the whole library" - it changes nothing on disk.',
            'report.showTracks': 'Show the audio tracks',
            'report.noTracksSelected': 'No track selected - nothing will be created',
            'report.rangeHigh': 'A wide gap between quiet and loud - this film is worth processing',
            'report.excluded': ' (excluded)',
            'report.hasOverride': 'This film has settings of its own',

            'summary.measured': 'Measured: <b>{measured}</b> · need processing (range above {target} LU): '
                + '<b>{worth}</b> · already done: <b>{done}</b>',
            'summary.median': 'Median range across the library: <b>{median} LU</b> · worst: {worstName} ({worstRange} LU)',
            'summary.remaining': '{n} left to process - roughly <b>{time}</b> of work and <b>{gb} GB</b> on disk.',
            'summary.nothing': 'Nothing needs processing with the current settings.',
            'unit.minutes': '{n} min',
            'unit.hours': '{n} h',

            'track.notScanned': 'Audio tracks have not been scanned yet. Run "Measure the whole library".',
            'track.normalizeThis': 'Normalize this track',
            'track.commentary': ' commentary',
            'track.manualChoice': 'Tracks were chosen by hand. ',
            'track.autoChoice': 'The track was chosen automatically by the rule in the settings. ',
            'track.resetAuto': 'Restore the automatic choice',

            'btn.build': 'Build',
            'btn.rebuild': 'Rebuild',
            'btn.delete': 'Delete',
            'btn.settings': 'Settings',
            'btn.settingsStar': 'Settings *',
            'btn.diagnostics': 'Diagnostics',
            'btn.exclude': 'Exclude',
            'btn.include': 'Include',
            'confirm.deleteTrack': 'Delete the normalized track? The original is not touched.',

            'sec.override': 'Settings for this film only:',
            'desc.override': 'These values apply to this film alone and override the global ones.',
            'btn.overrideSave': 'Save for this film',
            'btn.overrideReset': 'Back to the global settings',
            'btn.overrideClose': 'Close',
            'ov.loading': 'Loading…',
            'ov.loadFailed': 'Could not load the settings.',
            'ov.saved': 'Saved for this film.',
            'ov.saveFailed': 'Could not save the settings for this film.',
            'ov.targetLufs': 'Target loudness (LUFS)',
            'ov.maxPeak': 'Maximum peak (dBTP)',
            'ov.targetLra': 'Allowed range (LU)',
            'ov.skipBelow': 'Skip if below (LU)',
            'ov.engine': 'Engine',
            'ov.autoStrength': 'Pick the strength automatically',
            'ov.strength': 'Strength, 0-100',
            'ov.downmix': 'Layout',
            'ov.center': 'Centre (dialogue), dB',
            'ov.surround': 'Surrounds, dB',
            'ov.lfe': 'LFE subwoofer, dB',
            'ov.codec': 'Codec',
            'ov.bitrate': 'Bitrate, kbps',
            'ov.delay': 'Manual delay, ms',
            'short.engine.Dynaudnorm': 'dynaudnorm',
            'short.engine.SpeechNorm': 'speechnorm',
            'short.engine.Compressor': 'Compressor',
            'short.engine.LoudnessOnly': 'Loudness only',
            'short.downmix.DialogueStereo': 'Dialogue-forward stereo',
            'short.downmix.PlainStereo': 'Plain stereo',
            'short.downmix.KeepLayout': 'As in the original',

            'sec.selfTest': 'Self-test',
            'st.checking': 'Checking…',
            'st.film': 'Film',
            'st.file': 'File',
            'st.refusal': 'REFUSED: {reason}',
            'st.sourceTracks': 'Source audio tracks:',
            'st.chosen': 'Chosen',
            'st.outputPath': 'Output file',
            'st.folderWritable': 'Folder writable',
            'st.yes': 'yes',
            'st.no': 'NO',
            'st.freeSpace': 'Free disk space',
            'st.ffmpeg': 'ffmpeg',
            'st.strength': 'Strength (m)',
            'st.measured': 'Measured: {lufs} LUFS, range {range} LU, peak {peak} dBTP',
            'st.problems': 'PROBLEMS:',
            'st.analysisCommand': '--- analysis command (paste it into a terminal) ---',
            'st.encodeCommand': '--- encode command ---',
            'st.ffmpegOutput': '--- ffmpeg output ---',
            'st.requestFailed': 'The request failed: {error}',

            'state.Analyzed': 'measured',
            'state.Queued': 'queued',
            'state.Running': 'processing',
            'state.Done': 'done',
            'state.Skipped': 'skipped',
            'state.Failed': 'failed',
            'state.Stale': 'stale',
            'state.Unknown': 'unknown'
        },

        uk: {
            'lbl.language': 'Мова сторінки',

            'intro': 'Створює <strong>додаткову</strong> аудіодоріжку поруч із фільмом: діалоги гучніші, '
                + 'вибухи тихіші. Оригінальний файл не змінюється — у плеєрі просто з’являється ще один '
                + 'варіант звуку, між якими можна перемикатись.',

            'diag.title': 'Стан системи',
            'diag.checking': 'Перевіряю…',
            'diag.unknownPath': 'невідомо',
            'diag.missingFilters': 'Немає фільтрів: {list}',
            'diag.allFiltersPresent': 'Усі потрібні фільтри на місці.',
            'diag.candidates': 'Придатних до обробки одиниць медіа: {n}',
            'diag.failed': 'Не вдалось отримати стан.',

            'sec.thresholds': 'Пороги гучності',
            'lbl.targetLufs': 'Цільова гучність (LUFS)',
            'desc.targetLufs': 'Середній рівень готової доріжки. −16 підходить для перегляду вдома, '
                + '−23 — студійний стандарт (тихіше).',
            'lbl.maxPeak': 'Максимальний пік (dBTP) — верхній поріг',
            'desc.maxPeak': 'Стеля, вище якої звук не підніметься. −1.5 безпечно для будь-якого пристрою.',
            'lbl.targetLra': 'Допустима різниця тихе/гучне (LU)',
            'desc.targetLra': 'Скільки динаміки лишити. Бойовик зазвичай має 20–25 LU. '
                + '9 — комфортно вночі, 14 — ще «кінематографічно».',
            'lbl.skipBelow': 'Не обробляти, якщо різниця менша за (LU)',
            'desc.skipBelow': 'Рівному звуку друга доріжка нічого не дасть — тільки місце на диску.',

            'sec.processing': 'Обробка',
            'lbl.engine': 'Алгоритм',
            'desc.engine': 'Звичайний компресор лише прибирає гучне, але не робить діалоги чутнішими. '
                + 'dynaudnorm піднімає тихі місця — саме він розв’язує проблему.',
            'opt.engine.Dynaudnorm': 'dynaudnorm — підтягує тихе і притискає гучне (рекомендовано)',
            'opt.engine.SpeechNorm': 'speechnorm — орієнтований на мовлення',
            'opt.engine.Compressor': 'Компресор — найм’якший, зберігає найбільше динаміки',
            'opt.engine.LoudnessOnly': 'Лише вирівняти гучність, динаміку не чіпати',
            'chk.autoStrength': 'Підбирати силу автоматично під кожен фільм',
            'lbl.strength': 'Сила, 0–100',

            'sec.channels': 'Канали',
            'lbl.downmix': 'Розкладка',
            'desc.downmix': 'Звичайне зведення 5.1 → стерео робить діалоги <em>тихішими</em>: на тесті '
                + '−37.5 LUFS перетворилось на −44.8. Тому діалогова матриця — не забаганка.',
            'opt.downmix.DialogueStereo': 'Стерео з акцентом на діалог (рекомендовано)',
            'opt.downmix.PlainStereo': 'Звичайне стерео',
            'opt.downmix.KeepLayout': 'Лишити як в оригіналі (5.1/7.1)',
            'lbl.center': 'Центральний канал (діалоги), дБ',
            'lbl.surround': 'Тилові канали, дБ',
            'lbl.lfe': 'Сабвуфер LFE, дБ',
            'desc.lfe': '−60 вимикає LFE повністю. Саме там сидить більшість «бух» у бойовиках.',

            'sec.trackFile': 'Файл доріжки',
            'lbl.codec': 'Кодек',
            'opt.codec.Aac': 'AAC — грає всюди, включно з браузером (затримка 21 мс, компенсується)',
            'opt.codec.Eac3': 'E-AC3 — точна довжина, чудово для ТБ, браузер не тягне',
            'opt.codec.Ac3': 'AC3 — те саме, сумісніший зі старими ресиверами',
            'opt.codec.Flac': 'FLAC — без втрат, нульова затримка, файл у 3–5 разів більший',
            'opt.codec.Opus': 'Opus — найменший розмір, слабша підтримка на старих ТБ',
            'lbl.container': 'Контейнер',
            'opt.container.Mka': '.mka — зберігає мову і назву доріжки (рекомендовано)',
            'opt.container.M4a': '.m4a — зберігає мову, назву втрачає',
            'opt.container.Raw': 'Сирий потік — жодних тегів, лише ім’я файлу',
            'lbl.bitrate': 'Бітрейт, кбіт/с',
            'lbl.prefix': 'Префікс назви доріжки',
            'desc.prefix': 'Ставиться перед назвою: <code>AN - Ukrainian 5.1</code>. Так нормалізовані '
                + 'доріжки одразу видно в списку звуку плеєра.',
            'chk.appendSource': 'Додавати назву вихідної доріжки після префікса',
            'lbl.fallbackTitle': 'Запасна назва',
            'desc.fallbackTitle': 'Використовується, коли з вихідної доріжки нічого взяти. Не вживайте '
                + 'слова default, forced, foreign, cc, hi, sdh — Jellyfin прочитає їх як службові '
                + 'прапорці, а не як назву.',
            'chk.makeDefault': 'Зробити нормалізовану доріжку типовою',
            'lbl.delay': 'Ручна затримка, мс',
            'desc.delay': 'Лишіть 0. Потрібно лише якщо конкретний клієнт не враховує затримку кодека '
                + 'і звук помітно розходиться з відео.',

            'sec.background': 'Робота у фоні',
            'lbl.parallel': 'Паралельних завдань',
            'chk.pause': 'Ставити на паузу, поки хтось дивиться',
            'chk.dryRun': 'Тестовий прогін: нічого не записувати, лише показати що буде зроблено',
            'chk.logCommands': 'Писати повну команду ffmpeg у лог сервера',
            'lbl.minFree': 'Лишати вільного місця, ГБ',
            'lbl.minDuration': 'Пропускати коротше за, хв',
            'lbl.sourceSel': 'Яку доріжку брати за основу',
            'opt.src.MostChannels': 'З найбільшою кількістю каналів',
            'opt.src.DefaultTrack': 'Типову',
            'opt.src.PreferredLanguage': 'За бажаною мовою',
            'lbl.langs': 'Бажані мови, через кому',
            'btn.save': 'Зберегти',
            'msg.saveFailed': 'Не вдалось зберегти налаштування. Подробиці — в лозі сервера.',

            'sec.queue': 'Черга',
            'queue.line': 'У черзі: {pending} · виконується: {running} · завершено: {done} · помилок: {failed}',
            'queue.pausedPlayback': ' · призупинено, бо йде відтворення',
            'btn.analyzeAll': 'Виміряти всю бібліотеку',
            'btn.generateAll': 'Створити доріжки там, де треба',
            'btn.cancelQueue': 'Очистити чергу',
            'msg.queuedAnalyze': 'Поставлено в чергу на вимірювання: {n}',
            'msg.queuedGenerate': 'Поставлено в чергу на створення: {n}',
            'msg.dequeued': 'Знято з черги: {n}',

            'sec.report': 'Звіт по медіа',
            'chk.onlyProblems': 'Лише ті, де різниця перевищує ціль',
            'desc.report': 'Клацніть на <b>назву фільму</b>, щоб розгорнути список його аудіодоріжок і '
                + 'галочками обрати, які саме нормалізувати. Клацніть на заголовок колонки, щоб '
                + 'відсортувати. «Тихе» і «Гучне» — це межі, між якими гуляє гучність; «Різниця» між '
                + 'ними і є тим, що ріже вуха.',
            'th.name': 'Назва',
            'th.minutes': 'Хв',
            'th.tracks': 'Дор.',
            'th.tracks.tip': 'Скільки доріжок обрано для нормалізації',
            'th.source': 'Джерело',
            'th.lufs': 'LUFS',
            'th.lufs.tip': 'Середня гучність оригіналу',
            'th.range': 'Різниця',
            'th.range.tip': 'Різниця між тихим і гучним в оригіналі',
            'th.quiet': 'Тихе',
            'th.quiet.tip': 'Нижня межа гучності: приблизно рівень тихих діалогів',
            'th.loud': 'Гучне',
            'th.loud.tip': 'Верхня межа гучності: приблизно рівень гучних сцен',
            'th.peak': 'Пік',
            'th.peak.tip': 'Піковий рівень оригіналу',
            'th.after': 'Стало',
            'th.after.tip': 'Різниця після обробки',
            'th.state': 'Стан',
            'th.mb': 'МБ',

            'report.empty': 'Поки порожньо. Запустіть «Виміряти всю бібліотеку» — це нічого не змінює на диску.',
            'report.showTracks': 'Показати аудіодоріжки',
            'report.noTracksSelected': 'Жодної доріжки не обрано — нічого не буде створено',
            'report.rangeHigh': 'Велика різниця між тихим і гучним — цей фільм вартий обробки',
            'report.excluded': ' (виключено)',
            'report.hasOverride': 'Цей фільм має власні налаштування',

            'summary.measured': 'Виміряно: <b>{measured}</b> · потребують обробки (різниця більша за '
                + '{target} LU): <b>{worth}</b> · уже готово: <b>{done}</b>',
            'summary.median': 'Медіанна різниця по бібліотеці: <b>{median} LU</b> · найгірший: {worstName} ({worstRange} LU)',
            'summary.remaining': 'Лишилось обробити {n} — це приблизно <b>{time}</b> роботи і <b>{gb} ГБ</b> на диску.',
            'summary.nothing': 'Немає нічого, що потребувало б обробки за поточними налаштуваннями.',
            'unit.minutes': '{n} хв',
            'unit.hours': '{n} год',

            'track.notScanned': 'Аудіодоріжки ще не проскановано. Запустіть «Виміряти всю бібліотеку».',
            'track.normalizeThis': 'Нормалізувати цю доріжку',
            'track.commentary': ' коментар',
            'track.manualChoice': 'Доріжки обрано вручну. ',
            'track.autoChoice': 'Доріжку обрано автоматично за правилом із налаштувань. ',
            'track.resetAuto': 'Повернути автоматичний вибір',

            'btn.build': 'Створити',
            'btn.rebuild': 'Перебудувати',
            'btn.delete': 'Видалити',
            'btn.settings': 'Налаштування',
            'btn.settingsStar': 'Налаштування *',
            'btn.diagnostics': 'Діагностика',
            'btn.exclude': 'Виключити',
            'btn.include': 'Повернути',
            'confirm.deleteTrack': 'Видалити нормалізовану доріжку? Оригінал не постраждає.',

            'sec.override': 'Окремі налаштування:',
            'desc.override': 'Ці значення діють тільки для цього фільму й перекривають глобальні.',
            'btn.overrideSave': 'Зберегти для цього фільму',
            'btn.overrideReset': 'Повернути до глобальних',
            'btn.overrideClose': 'Закрити',
            'ov.loading': 'Завантажую…',
            'ov.loadFailed': 'Не вдалось завантажити налаштування.',
            'ov.saved': 'Збережено для цього фільму.',
            'ov.saveFailed': 'Не вдалось зберегти налаштування для цього фільму.',
            'ov.targetLufs': 'Цільова гучність (LUFS)',
            'ov.maxPeak': 'Максимальний пік (dBTP)',
            'ov.targetLra': 'Допустима різниця (LU)',
            'ov.skipBelow': 'Не обробляти якщо менше (LU)',
            'ov.engine': 'Алгоритм',
            'ov.autoStrength': 'Підбирати силу автоматично',
            'ov.strength': 'Сила, 0–100',
            'ov.downmix': 'Розкладка',
            'ov.center': 'Центр (діалоги), дБ',
            'ov.surround': 'Тили, дБ',
            'ov.lfe': 'Сабвуфер LFE, дБ',
            'ov.codec': 'Кодек',
            'ov.bitrate': 'Бітрейт, кбіт/с',
            'ov.delay': 'Ручна затримка, мс',
            'short.engine.Dynaudnorm': 'dynaudnorm',
            'short.engine.SpeechNorm': 'speechnorm',
            'short.engine.Compressor': 'Компресор',
            'short.engine.LoudnessOnly': 'Лише гучність',
            'short.downmix.DialogueStereo': 'Стерео з акцентом на діалог',
            'short.downmix.PlainStereo': 'Звичайне стерео',
            'short.downmix.KeepLayout': 'Як в оригіналі',

            'sec.selfTest': 'Самодіагностика',
            'st.checking': 'Перевіряю…',
            'st.film': 'Фільм',
            'st.file': 'Файл',
            'st.refusal': 'ВІДМОВА: {reason}',
            'st.sourceTracks': 'Аудіодоріжки джерела:',
            'st.chosen': 'Обрано',
            'st.outputPath': 'Куди ляже файл',
            'st.folderWritable': 'Тека доступна',
            'st.yes': 'так',
            'st.no': 'НІ',
            'st.freeSpace': 'Вільно на диску',
            'st.ffmpeg': 'ffmpeg',
            'st.strength': 'Сила (m)',
            'st.measured': 'Виміряно: {lufs} LUFS, різниця {range} LU, пік {peak} dBTP',
            'st.problems': 'ПРОБЛЕМИ:',
            'st.analysisCommand': '--- команда аналізу (можна вставити в термінал) ---',
            'st.encodeCommand': '--- команда кодування ---',
            'st.ffmpegOutput': '--- вивід ffmpeg ---',
            'st.requestFailed': 'Запит не вдався: {error}',

            'state.Analyzed': 'виміряно',
            'state.Queued': 'у черзі',
            'state.Running': 'обробляється',
            'state.Done': 'готово',
            'state.Skipped': 'пропущено',
            'state.Failed': 'помилка',
            'state.Stale': 'застаріло',
            'state.Unknown': 'невідомо'
        }
    };
})();
